version: 2

sources:
  - name: nyc_ems_calls_dataset
    description: 'bigquery databse for nyc ems calls and related tables'
    database: ny-rides-gregl-446219  
    schema: nyc_ems_calls_dataset  
    tables:
      - name: nyc_ems_calls 
        columns:
          - name: cad_incident_id
            tests: 
              - unique
              - not_null